---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: helm-toolkit
data:
  chart_name: helm-toolkit
  release: helm-toolkit
  namespace: helm-toolkit
  values: {}
  source:
    type: local
    location: ${OSH_INFRA_PATH}
    subpath: helm-toolkit
    reference: master
  dependencies: []
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tempest
data:
  chart_name: tempest
  release: tempest
  namespace: openstack
  wait:
    timeout: 7200
    labels:
      release_group: osh-tempest
  install:
    no_hooks: False
  upgrade:
    no_hooks: False
    pre:
      delete:
        - type: job
          labels:
            release_group: osh-tempest
  values:
    images:
      tags:
        dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
        tempest_run_tests: docker.io/kolla/ubuntu-source-tempest:3.0.3
        ks_user: docker.io/openstackhelm/heat:newton
        image_repo_sync: docker.io/docker:17.07.0
    labels:
      job:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    conf:
      tempest:
        service_available:
          cinder: true
          glance: true
          neutron: true
          nova: true
      compute:
        flavor_ref: ${FLAVOR_ID}
        image_ref: ${IMAGE_ID}
        image_ref_alt: ${IMAGE_ID}
        hypervisor_type: ${HYPERVISOR_TYPE}
      network:
        default_network: ${OSH_PRIVATE_SUBNET_POOL}
        project_network_cidr: 172.0.4.0/16
        floating_network_name: "public"
        public_network_id: ${NETWORK_ID}
      validation:
        image_ssh_user: "cirros"
        image_ssh_password: "gocubsgo"
        network_for_ssh: "public"
        floating_ip_range: ${OSH_EXT_SUBNET}
    pvc:
      enabled: false
  source:
    type: local
    location: ${OSH_PATH}
    subpath: tempest
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: execute-tempest
data:
  description: "Run Tempest against OpenStack-Helm"
  sequenced: False
  chart_group:
    - tempest
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: tempest-armada-manifest
data:
  release_prefix: osh
  chart_groups:
    - execute-tempest
